rails_tut:
  home: "https://www.railstutorial.org/"
  book: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  help: "https://www.railstutorial.org/help"
  screencasts: "http://screencasts.railstutorial.org/"
  news: "http://news.railstutorial.org/"

validates:
  user:
    maximum_name: 50
    maximum_email: 255
    minimum_pass: 6
  micropost:
    maximum_content: 140

helper:
  users:
    size: 80

rails_web:
  home: "http://rubyonrails.org/"

michael_hartl:
  home: "http://www.michaelhartl.com/"

gravatar:
  email: "http://gravatar.com/emails"

img:
  kitty: "kitten.jpg"
  rails_logo: "rails.png"

views:
  users:
    user:
      size: 50
  microposts:
    micropost:
      size: 50
  shared:
    user_info:
      size: 50

controllers:
  users:
    pag: 10
  microposts:
    pag: 10
  static_pages:
    pag: 10

models:
  user:
    waiting_time: 2
  micropost:
    pic_size: 5

picture:
  formats: "image/jpeg,image/gif,image/png"
  resize: 400
