rails_tut:
  home: "https://www.railstutorial.org/"
  book: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  help: "https://www.railstutorial.org/help"
  screencasts: "http://screencasts.railstutorial.org/"
  news: "http://news.railstutorial.org/"
rails_web:
  home: "http://rubyonrails.org/"
michael_hartl:
  home: "http://www.michaelhartl.com/"
img:
  kitty: "kitten.jpg"
  rails_logo: "rails.png"
